name: PKUAutoSubmit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "25 3 * * *"
    - cron: "45 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yousiki/PKUAutoSubmit-action@master
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          reason: "上课"
          wechat: "False"
          in_street: "青龙桥"
          out_track: "燕园-圆明园"
          sckey: "xxxxxxxx"
